### ISSUE TITLE
Pb https

### ISSUE THREAD

**Issue by ssonnet** [OpenEdition/lodel#103]
Bonjour,

Nous sommes en train de mettre en place Lodel pour la pré-production et nous rencontrons un problème avec le https. J'ai pu faire l'installation en mode sécurisé, par contre après installation, lors de mes tentatives de connexion/déconnexion à l'admin, je tombais sur une page blanche avec l'erreur suivante :

<code>
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
</code>

Le "https" était enlevé de l'url et apparaissait à la place un ":443" à la fin de l'url...

Nous avons désactivé le https mais souhaiterions pouvoir le mettre en place : avez-vous des conseils ? La mise en place du https chez OpenEdition a-t-elle nécessité des adaptations du code de Lodel ?

Cordialement.

**Comment by nahuelange** [comment]
J'espère que c'est toujours le cas!
@jfriviere une réponse ?

**Comment by lnprieto** [comment]
Bonjour
En effet faire des pull requests est un bon moyen pour proposer des corrections à intégrer dans la branche master.
Les modifications proposées ici ont été intégrées dans master.
Merci
Bien cordialement

**Comment by nahuelange** [comment]
Si ça a été intégré, cette issue peut-être fermée j'imagine?

**Comment by nahuelange** [comment]
Je viens de faire une PR concernant ce problème : https://github.com/OpenEdition/lodel/pull/122
