### ISSUE TITLE
Table individus

### ISSUE THREAD

**Issue by ssonnet** [OpenEdition/lodel#104]
Bonjour,

J'ai commencé à migrer plusieurs sites de revue en utilisant pour l'instant le jeu de templates par défaut du modèle éditorial OJE. L'un de ces sites n'a pas de table "individus", ce qui génère une erreur car les données de cette table sont appelées dans la macro INSERER_FEUILLE_DE_STYLE. J'ai donc 2 options :

- créer la table individus
- supprimer l'appel des données dans le jeu de templates

Je constate que si tous les autres sites ont bien la table individus, elle est toutefois toujours vide... d'ailleurs, je n'ai pas trouvé comment l'alimenter via le CMS. Cette table a-t-elle une utilité ?

Cordialement.

**Comment by jfriviere** [comment]
Bonjour, la table individus existe si un classe individus est définie dans le modèle éditorial du site. 
Et le template fait des requêtes sur la table individus pour afficher les éléments de cette classe. 

- Si cette classe n'est jamais utilisée, elle peut être supprimée du modèle éditorial et des templates. Dans ce cas, il faut utiliser l'outils d'administration du modèle éditorial pour supprimer la classe "individus" (ne pas supprimer directement la table "individus" dans MySQL).

- autre option : si le template doit permettre d'afficher des sites qui contiennent la classe individus et d'autres qui ne la contiennent pas, on peut ajouter un test d'existence de la classe dans le template . Quelque chose dans ce genre en lodelscript : 
```
<LOOP NAME="testindividus" TABLE="classes" WHERE="classtype = 'entities'  AND class='individus'" MILIT="1"> 
<!--[ si la classe d'entitié "individus" existe ]-->
   <LOOP NAME="displayindividus" TABLE="individus">
     ....
   </LOOP> 
</LOOP>

```

**Comment by ssonnet** [comment]
Merci pour votre réponse. Pour l'instant, je vais opter pour la deuxième option avec le test d'existence de la classe. Je viens d'essayer ça marche, par contre juste pour ceux qui liraient les échanges il y a une petite coquille dans les paramètres de la première boucle : c'est LIMIT et non pas MILIT.

**Comment by jfriviere** [comment]
Merci pour le retour. J'ai corrigé MILIT/LIMIT dans ma réponse.
