### ISSUE TITLE
Problème de multilinguisme

### ISSUE THREAD

**Issue by SylDanh** [OpenEdition/lodel#106]
Bonjour,

Je rencontre un problème avec le 'Multilinguisme'.

Je suis sur une machine ubuntu 18.04.1, PHP 7.0.33-8+ubuntu18.04.1.

J’installe lodel avec "git clone https://github.com/OpenEdition/lodel.git".

Je crée un site en utilisant "Modèle Editorial OEJ" comme modèle éditorial.

Ensuite je me rends sur la page d'accueil de mon site avec un autre navigateur en mode non identifié.

Et je teste le multilinguisme (https://github.com/OpenEdition/lodel/wiki/Lodelscript#multilinguisme point 4).

    http://php70.example.com/sitedetest/index.php?lang=en
    http://php70.example.com/sitedetest/index.php?lang=es

Mais rien ne change, aucun mot n'est traduit.

D'avance merci pour votre aide.

**Comment by SylDanh** [comment]
Bonjour,

Dans mon cas, c'est le fichier 'index.html' avec pour objet de test la ligne 
`<h1>[@COMMON.TESTMULTILINGUISME] [#SITELANG]</h1>`

Je fait également le test d'affichage de la valeur contenu dans la variable Lodelscript [#SITELANG].

J’ajoute également des prints screen

D'avance merci pour votre aide.

Sylvain Danhieux


[index.txt](https://github.com/OpenEdition/lodel/files/3290013/index.txt)


![Screenshot_2019-06-14 Site de Test](https://user-images.githubusercontent.com/35763563/59499661-2648f700-8e98-11e9-823a-79c3408cffbb.png)
![Screenshot_2019-06-14 Site de Test(1)](https://user-images.githubusercontent.com/35763563/59499662-2648f700-8e98-11e9-931f-583f29b45184.png)
![Capture d’écran de 2019-06-14 11-25-10](https://user-images.githubusercontent.com/35763563/59499656-2517ca00-8e98-11e9-9f65-b50c889c42a5.png)
![Capture d’écran de 2019-06-14 11-25-16](https://user-images.githubusercontent.com/35763563/59499657-2517ca00-8e98-11e9-91f7-dca063c6faeb.png)
![Capture d’écran de 2019-06-14 11-25-22](https://user-images.githubusercontent.com/35763563/59499658-25b06080-8e98-11e9-99ff-2e5bcff7c23e.png)
![Capture d’écran de 2019-06-14 11-25-33](https://user-images.githubusercontent.com/35763563/59499659-25b06080-8e98-11e9-9f4d-bb19588d5df9.png)
![Screenshot_2019-06-14 Panneau d'administration des traductions du site](https://user-images.githubusercontent.com/35763563/59499660-25b06080-8e98-11e9-8537-c6a2f0ebe9e8.png)

**Comment by brrd** [comment]
@SylDanh avez-vous essayé la variable `[@TESTMULTILINGUISME]` ?

**Comment by brrd** [comment]
Et en ce qui concerne `[#SITELANG]`, avez-vous bien renseigné la langue dans les options du site ?

**Comment by SylDanh** [comment]
Bonjour @brrd 

Alors avec [@TESTMULTILINGUISME], ne fonctionne pas car pas de textgroup.
et oui le [#SITELANG] est bien renseigné.

![Screenshot_2019-06-14 Options du site](https://user-images.githubusercontent.com/35763563/59501104-20a0e080-8e9b-11e9-91b7-cf21aa650b79.png)

**Comment by brrd** [comment]
Je dis peut-être une bêtise mais il me semble que le groupe COMMON est utilisé au niveau lodeladmin pour les templates du backoffice de Lodel. Pas sûr que ce soit utilisable dans les templates publics. 

Essayez de renseigner les variables dans le groupe SITE accessible depuis l'administration du site (url du type `nomdusite/lodel/admin/index.php?do=list&lo=translations`). La syntaxe simple `[@TESTMULTILINGUISME]` devrait fonctionner avec ces variables. C'est en tout cas comme ça que j'ai toujours travaillé.

Aucune idée en revanche pour le `[#SITELANG]`. @jfriviere sera sans doute mieux inspiré.

**Comment by jfriviere** [comment]
Oui, c'est ça @brrd, il faut utiliser **les traductions du SITE** (LODEL_URL/MON_SITE/lodel/admin/index.php?do=list&lo=translations) , pas celles de l'interface d'admin de Lodel (LODEL_URL/lodeladmin/index.php?do=list&lo=translations)
 
Je précise qu'on parle ici de 3 choses qui sont liées mais distinctes :

### la valeur de la variable `[#SITELANG]` générée par Lodel
Il faut d'abord ajouter une traduction ici :  SITE_URL/lodel/admin/index.php?do=list&lo=translations
J'ajoute par exemple la traduction "fr"

- je consulte une page du site avec un template qui affiche `[#SITELANG]` (par exemple http://php70.example.com/sitedetest/index.php), le template affichera "fr".
- je consulte http://php70.example.com/sitedetest/index.php?lang=en, le template affichera toujours "fr". Le paramètre GET "lang" n'est pris en compte que site la langue est déclaré dans les traductions du site : SITE_URL/lodel/admin/index.php?do=list&lo=translations
- si j'ajoute dans SITE_URL/lodel/admin/index.php?do=list&lo=translation la tracution "en", http://php70.example.com/sitedetest/index.php?lang=en  affichera bien "en"
- Attention, quand on est logué comme utilisateur Lodel `[#SITELANG]` est toujours égal à la langue de l'utilisateur, indépendamment du paramètre GET "lang" et du cookie "lang). Pour tester, il faut donc consulter la page en étant déconnecté de Lodel.

### les variables de traductions `[@MA_VARIABLE]` utilisées dans les templates du site
- j'ajoute ensuite dans mon template ` [@MA_VARIABLE] `
- dans  SITE_URL/lodel/admin/index.php?do=list&lo=translations, on peut cliquer en haut à droite sur "Rechercher toutes les variables dans tous les templates" ce qui ajoutera l'entrée MA_VARIABLE dans la liste des éléments traduisibles. (si on consulte la page contenant `[@MA_VARIABLE]` Lodel va aussi ajouter l'entrée MA_VARIABLE dans les traductions si elle n'existe pas)
- je peux renseigner les valeurs "fr" et "en" de MA_VARIABLE. Elle s'afficheront respectivement dans les pages :
http://php70.example.com/sitedetest/index.php?lang=en
http://php70.example.com/sitedetest/index.php?lang=es

### Champs multilingues 
- pour afficher le résumé (champ multilingue) en fonction de la langue de navigation :
`[#RESUME:#SITELANG]`
- pour afficher les résumés dans toutes les langues : 

```
<IF COND="[#RESUME] LIKE /<r2r:ml lang=\"([a-z]+)\"/">
    <LOOP NAME="foreach" ARRAY="[#MATCHES.1]">
        <div lang="[#VALUE]" xml:lang="[#VALUE]">
             [#RESUME:#VALUE]
        </div>
    </LOOP>
</IF>

```

**Comment by brrd** [comment]
Super ! Le problème est donc résolu ?

**Comment by SylDanh** [comment]
Waaaaaaaaaw Merci.

C'est donc maintenant corrigé.
