### ISSUE TITLE
Fermeture Servoo ?

### ISSUE THREAD

**Issue by ssonnet** [OpenEdition/lodel#110]
Bonjour,
On m'a alerté ce matin de l'impossibilité d'importer un article dans notre plateforme lodel 0.9. A tout hasard, auriez-vous fermé le SERVOO (c'était prévu pour juin) ? Ou est-ce un pb "passager" ?
Bien cordialement.

**Comment by jcsouplet** [comment]
Bonjour,

Comme prévu et annoncé, notre instance SERVOO a en effet bien été fermée.

Bien cordialement,

JC

**Comment by ssonnet** [comment]
Merci pour votre réponse.
Bien cordialement.
