### ISSUE TITLE
Champ "date de publication électronique"

### ISSUE THREAD

**Issue by ssonnet** [OpenEdition/lodel#113]
Bonjour,

Dans le modèle éditorial de nos revues figure un champ [#DATEPUBLI] (date de publication électronique). Malheureusement je constate que le fait de publier un document au travers de l'admin n'a aucun effet sur ce champ. Est-il possible de faire en sorte qu'il soit alimenté automatiquement par la date du jour lorsque l'on clique sur "publier" dans l'admin ?

Cordialement.
Sylvain Sonnet

**Comment by ssonnet** [comment]
Re-bonjour,

Désolé, j'ai trouvé la réponse à ma question... je la donne si ça peut aider d'autres personnes : dans le champ "@hooks_for_edition" j'ai saisi la valeur "updatedatepubli" (dans le formulaire de définition de champ pour personnaliser le modèle éditorial). Cette valeur correspond à un hook (une fonction php) présente dans le fichier /lodel/scripts/hookfunc.php

Cordialement.

**Comment by jfriviere** [comment]
Bonjour,
Je confirme que c'est la bonne approche. 
J'ajoute que dans le cas où des entitées descendantes (par exemple des articles) de l'entitié publiées (le numéro) disposeraient du même champ (ici [#DATEPUBLI]), celui-ci sera aussi défini à la date de publication de l'entité parente.

https://github.com/OpenEdition/lodel/blob/master/lodel/scripts/hookfunc.php#L26-L38

Cordialement
JF Rivière
