### ISSUE TITLE
Pb caractères accentués dans templates

### ISSUE THREAD

**Issue by ssonnet** [OpenEdition/lodel#114]
Bonjour,

Je suis parti des templates fournis avec Lodel pour concevoir l'interface de nos revues. Un certain nombre de ces templates commencent par la balise `<CONTENT VERSION="1.0" LANG="fr" CHARSET="utf-8"/>`. Celle-ci étant obsolète et le charset utf-8 étant déjà paramétré via une balise meta dans l'en-tête html, je l'ai retirée. Sauf qu'en faisant ça plus aucun caractère accentué statique dans les templates ne s'affiche correctement. Mes fichiers templates semblent bien en utf-8 (vérifié avec un file -i). Quand je fais une page html ou php toute simple hors installation Lodel et affichant "aéèuà", tout se passe bien, donc je ne pense pas avoir de problème de config serveur. Voyez vous une explication qui pourrait être liée à Lodel ?

Cordialement.
Sylvain Sonnet

**Comment by jfriviere** [comment]
Bonjour,  
Vous dites :

> Un certain nombre de ces templates commencent par la balise .

Mais il n'y a pas la balise. 
Pouvez-vous l'indiquer en utilisant les "quotes" qui permettent l'affichage du code dans le ticket ?
JFR

**Comment by brrd** [comment]
Je fais remonter ici cette version desdits templates ou l'encodage a été corrigé : https://github.com/edinum/lodel-default-template

Avec notamment ces deux commits qui pourront vous intéresser @ssonnet :
* https://github.com/edinum/lodel-default-template/commit/2d0c736ef08fc772d5859539a30459da7a32dab5
* https://github.com/edinum/lodel-default-template/commit/88a6771743961164cd091de0ab18748f11bd20d5

Sinon pour une nouvelle maquette en HTML5, libre, responsive et customisable, nous avons diffusé la Nova au début de l'année (en collaboration avec l'Université Jean Moulin Lyon 3) : https://github.com/edinum/nova

**Comment by ssonnet** [comment]
> Bonjour,
> Vous dites :
> 
> > Un certain nombre de ces templates commencent par la balise .
> 
> Mais il n'y a pas la balise.
> Pouvez-vous l'indiquer en utilisant les "quotes" qui permettent l'affichage du code dans le ticket ?
> JFR

Excusez moi, je n'avais pas fait attention, j'ai mis à jour le message il s'agit de la balise `<CONTENT VERSION="1.0" LANG="fr" CHARSET="utf-8"/>`

**Comment by jfriviere** [comment]
Je ne sais pas exactement comment cette balise est utilisée par Lodel, mais elle l'est, manifestement. Donc, je vous recommande de la laisser dans la template. Elle n'apparaitra pas dans la page html générée à partir du template.

Sinon @brrd a donné un lien vers une version du template de base (qui date de presque avant UTF-8...) dans laquelle les caractères accentués mal encodés sont corrigés.
JFR

**Comment by ssonnet** [comment]
Merci @brrd mais j'avais pris soin de convertir les templates en utf8 en début de projet (car par défaut beaucoup étaient en ISO_8859-1) et de vérifier les caractères accentués dans le code source.
Par contre, autant pour moi je n'avais pas compris que `<CONTENT>` était une balise propre à Lodel. Du coup en cherchant dans le code j'ai trouvé l'explication à mon problème dans le script parser.php :

- la fonction parse_main() ne définit le charset que si elle trouve une balise `<CONTENT>` :

`case 'CONTENT' :`
`$attrs = $this->_decode_attributs($this->arr[$this->ind + 1]);`
`$this->charset = isset($attrs['CHARSET']) ? $attrs['CHARSET'] : "utf-8";`

- et si le charset n'est pas défini dans la fonction parse(), le contenu de la page est obligatoirement converti en utf8 :

`if ($this->charset != 'utf-8') {`
`  #$t=microtime();`
`  function_exists('convertHTMLtoUTF8') || include 'utf8.php'; // conversion des caracteres`
`  $template['contents'] = utf8_encode($template['contents']);`
`  convertHTMLtoUTF8($template['contents']);`
`}`

Tout ça fait que s'il n'y a pas au minimum la balise `<CONTENT>` dans le template, alors Lodel convertit le contenu en uft8. Or si le contenu est déjà en utf8 (ce qui est mon cas), la fonction utf8_encode() produit l'effet inverse de celui escompté : on se retrouve avec des mauvais caractères accentués (https://www.php.net/manual/fr/function.utf8-encode.php).

Par contre si vous pouvez me dire à quoi servent les attributs VERSION et LANG, je suis preneur :)
