### ISSUE TITLE
Pb après upgrade OEJ.EM 1.0.x => 1.0.2

### ISSUE THREAD

**Issue by ssonnet** [OpenEdition/lodel#117]
Bonjour,

J'ai testé l'upgrade du modèle éditorial vers la version 1.0.2 (https://github.com/OpenEdition/oej.em/blob/master/upgrade/upgrade_1.0.X_to_1.0.2.php) sur un site en test. La MAJ s'est bien passée par contre désormais certaines métadonnées (à priori les métadonnées concernées par le script de migration : pagination et date de publi papier), après import du fichier word, se retrouvent dans la variable [#TEXTE ] et non plus dans leur variable propre (ex. [#PAGINATION]). Est-ce qu'il me manque quelque chose ou est-ce normal ?

Cordialement.
Sylvain Sonnet

**Comment by carmona-m** [comment]
Bonjour,

La version 1.0.2 du modèle éditorial est compatible avec le schéma TEI OpenEdition 1.6.2. Pour convertir vos fichiers Word dans cette version du schéma vous devez mettre à jour OTX (version 1.2.0 : https://github.com/OpenEdition/OTX/releases/tag/v1.2.0)

Pour en savoir plus : https://tei-openedition.readthedocs.io/fr/latest/compatibility.html

Cordialement,
Mélanie Carmona

**Comment by ssonnet** [comment]
Bonjour,
Je pensais avoir la dernière version d'OTX, mais effectivement vous avez raison ce n'était pas le cas. J'ai updaté OTX et ça marche. Au passage, j'en ai profité pour demander s'il vous était possible d'indiquer le numéro de version d'OTX dans ses sources : https://github.com/OpenEdition/OTX/issues/10. Un grep sur les sources OTX sur mon serveur ne m'a rien renvoyé, c'est dommage...
Cordialement.
Sylvain Sonnet

**Comment by ssonnet** [comment]
Bonjour,
J'ai fait la mise à jour sur le serveur de production et là : problème à l'import de fichier word. En activant le debug, j'ai une erreur  "DataLogic::generateXML(): Invalid Document Encoding" (ligne 2224). Après inspection il se trouve que mes bases en production sont en utf8mb4_unicode_ci alors que celles en dev (où je n'ai pas de problème) sont en utf8mb4_general_ci. En passant juste la base lodel de dev en utf8mb4_unicode_ci je reproduis l'erreur de la prod. Je suppose que le souci vient de la nouvelle version 1.2.0 d'OTX (car je n'avais pas le pb avec la version 1.1.2) ?
Cordialement.
Sylvain Sonnet

**Comment by ssonnet** [comment]
Bonjour,

J'ai procédé à la mise à jour du modèle éditorial hier sur le serveur de production, et j'ai un souci. Pour info, j'ai également mis à jour OTX et Lodel sur la base de leur branche master. Le problème rencontré est le suivant. Lorsque j'importe le fichier Word, tout se passe bien jusqu'à la validation du formulaire d'édition. Mais au moment de conclure et de valider le formulaire :
- un message d'erreur s'affiche ("Une ou plusieurs erreurs se trouvent dans le formulaire et empêchent de le valider :"),
- les dates de création et de modification passent au 1er janvier 1970,
- le champs "Texte du document" apparait vide

J'ai activé le debug et sur deux champs non renseignés (titre alternatif et texte au format pdf) j'obtiens l'erreur php suivante :

`PHP Error (Notice) in file '/var/www/html/lodel/lodel/scripts/view.php(523) : eval()'d code' on line 1222 : 
Array to string conversion`

Avez-vous une idée  ?
Cordialement.
Sylvain Sonnet

**Comment by ssonnet** [comment]
Bonjour,

Je suis toujours en train d'investiguer et j'ai trouvé l'endroit où ça bloque dans Lodel sur le serveur de production :

`/* Vérification de modification concurrente */`
`if ( isset($context['timestamp']) && (int)$context['timestamp'] < strtotime($vo->upd)) {`
`    $error['concurrent'] = "concurrent_edition";`
`    return "_error";`
`}`

Sur mon environnement de dev, les 2 timestamp sont de même valeur, donc pas d'erreur. Mais sur la prod ils diffèrent et l'erreur "concurrent_edition" est renvoyée.
A ce stade j'aurais tendance à émettre l'hypothèse d'un problème de paramétrage d'environnement système ? Je vais continuer à chercher mais est-ce que vous auriez une piste ?

Bien cordialement.
Sylvain Sonnet

**Comment by jfriviere** [comment]
Bonjour,
Nous avons déjà rencontré ce type d'erreur avec Lodel dans un environnement distribué composé de plusieurs machine virtuelle (VM). Il y avait des différences d'heure entre les VM. Cela produisait cette erreur.
Après avoir installé NTP pour synchroniser l'heure sur les différentes VM, le pb a été résolu.
JF Rivière

**Comment by ssonnet** [comment]
Bonjour,
En effet il s'agissait bien d'un problème de "décalage horaire" sur les 2 VM. Merci pour votre aide.
Bien cordialement.
Sylvain Sonnet
