### ISSUE TITLE
Aperçu des liens / Métadonnées d'un site Lodel

### ISSUE THREAD

**Issue by fabienbp** [OpenEdition/lodel#118]
Bonjour,

Nous rencontrons un problème avec [https://publications-prairial.fr/frontiere-s/](https://publications-prairial.fr/frontiere-s/) Lorsque nous partageons les liens, il semble que les métadonnées, pourtant renseignées, ne soit pas utilisées. Du coup sur Facebook par exemple, cela affiche un cadre totalement déconnecté du contenu : même le nom du site n'est pas chargé !

![Capture](https://user-images.githubusercontent.com/61978417/77327829-01818a00-6d1c-11ea-91e4-837c08e1f005.JPG)

L'outil de debug de Facebook indique notamment "Les propriétés requises suivantes manquent : og:url, og:type, og:title, og:image, og:description, fb:app_id", en plus de [3 autres alertes. ](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fpublications-prairial.fr%2Ffrontiere-s%2Findex.php%3Fid%3D150)

Où pouvons-nous modifier les données afin de corriger cela ? Merci !

Cordialement.

**Comment by jfriviere** [comment]
Bonjour,
C'est vraisemblablement une question de la maquette Prairial. 
Je pense qu'il faut plutôt l'adresser sur ce dépot Github : https://github.com/edinum/prairial
JF Rivière

**Comment by brrd** [comment]
@fabienbp Pour l'instant les métadonnées OpenGraph utilisées par Facebook ne sont pas exposées par la maquette de votre site.

@jfriviere Plus précisément le dépôt concerné est https://github.com/edinum/nova

Je viens d'y créer un ticket (https://github.com/edinum/nova/issues/72) à privilégier pour continuer cette conversation.

**Comment by fabienbp** [comment]
Merci beaucoup de vos réponses et du nouveau ticket ! Le problème ne vient à priori par de Prairial du coup, mais d'Edinum ?

**Comment by brrd** [comment]
> Merci beaucoup de vos réponses et du nouveau ticket ! Le problème ne vient à priori par de Prairial du coup, mais d'Edinum ?

Edinum est un collectif de prestataires qui a développé deux maquettes Lodel pour Lyon 3, publiées sous licence libre :
* Prairial (https://github.com/edinum/prairial) est la maquette du portail https://publications-prairial.fr/accueil/
* La Nova (https://github.com/edinum/nova) est la maquette libre pour les revues

C'est ce dernier projet qui ne supporte pas les métadonnées OpenGraph dans sa version actuelle. Le projet est maintenu par Edinum sur Github, mais il est ouvert aux contributions extérieures selon les modalités habituelles de Github (pull requests).

Je vous recommande de faire remonter le problème aux Bibliothèques universitaires de l'Université Jean Moulin Lyon 3 avec qui nous continuons travaillons pour savoir si ce développement doit être intégré à nos futures interventions.

**Comment by fabienbp** [comment]
Merci pour ces précisions. J'ai transmis à nos contacts de Prairial !
