### ISSUE TITLE
Faille XSS sur la page de connexion

### ISSUE THREAD

**Issue by SushiDa** [OpenEdition/lodel#142]
Bonjour, il y a une faille XSS à la connexion de l'admin.

Pour le tester c'est simple : 
- Aller sur une page de login (admin générale ou celle d'un site)
- Entrer dans le login le texte suivant : "><script>alert("XSS")</script>
- Envoyer le formulaire, le script devrait être exécuté

**Comment by fbridebian** [comment]
La PR https://github.com/OpenEdition/lodel/pull/143 qui a été mergée doit corriger ce problème
