### ISSUE TITLE
Importer du LaTeX ?

### ISSUE THREAD

**Issue by joelgombin** [OpenEdition/lodel#47]
Par curiosité, et ne connaissant pas le fonctionnement détaillé de Lodel, je me demandais s'il était envisageable, et si oui quelle quantité d'efforts cela requerrait, de faire en sorte que Lodel puisse accepter du LaTeX en entrée ?

**Comment by arnaudcordier** [comment]
En s'inspirant de lodel/scripts/teiparser.php cela doit être faisable.
Ce n'est pas quelque chose que nous avons envisagé pour l'instant.
