### ISSUE TITLE
Installation impossible avec PHP 5.6

### ISSUE THREAD

**Issue by pyg77** [OpenEdition/lodel#49]
A priori, Lodel utilise encore AdoDB avec des appels à la fonction mysql_connect.
https://github.com/OpenEdition/lodel/search?utf8=%E2%9C%93&q=mysql_connect

Or celle-ci n'est plus supportée depuis un moment : http://php.net/manual/fr/function.mysql-connect.php

Y a-t-il un moyen de contourner ce problème ?
(J'ai bien vu l'issue #17 mais depuis janvier, je ne vois pas de modifications de ce côté)

**Comment by flartet** [comment]
Puisque j'ai un début de réponse.

./lodel/install/plateform/lodelconfig-default.php
C'est là que l'on trouve les drivers par défaut.
`$cfg['dbDriver']` = 'mysqli';`

Une fois cela modifié, le log Apache ne fait plus de remarque à ce sujet.

**Comment by arnaudcordier** [comment]
af6e76677d861acccc61e1d6c133c7e01b7409f6 devrait régler le problème
