### ISSUE TITLE
Installation impossible, tout court

### ISSUE THREAD

**Issue by flartet** [OpenEdition/lodel#53]
Bonjour,
depuis 2j, je me bats avec Lodel sur des points qui me semblent devoir fonctionner a minima. Soit je n'ai rien compris, soit le processus d'installation est à corriger.

Installation tentée à partir du "master" ainsi que du tag 1.0.2

Création d'un site
`Error (Internal Error) in file '/var/www/html/lodel/scripts/class.siteManage.php' on line 326 :
SQL ERROR :
Field 'langdef' doesn't have a default value`

Soit, j'ajoute une valeur par défaut. Il faut aussi le faire pour le champ 'lang'.

Ensuite, création de la base de données, il y a une erreur sur les droits utilisateur mais celle-ci est bien créée tout de même.

Ensuite (page site.php), page blanche avec ceci écrit :
`getIncTpl($context,"desk","", $this->_home."../tpl/"); ?>
Création d'un site
@fail_for_table_creation.
@check_database_user_rights_who_must_be_able_to_create_tables.
@command_list_making_errors_and_database_server_errors : `

Comme je suis têtu, après avoir fouiné le code et les divers eval, il s'avère qu'il manque carrément une fonction `loop_errors_createtables`.
Soit, on la rajoute dans loops.php
`function loop_errors_createtables(&$context, $funcname, $rien = array()) {`
`        $website = new siteManage();`
`        $website->loop_errors_createtables($context, $funcname);`
`}`

Vient ensuite : 
Error (Internal Error) in file '/var/www/html/lodel/scripts/view.php' on line 764 :
Internal error in file /var/www/html/lodel/scripts/view.php(579) : eval()'d code on line 71;
LOOP: nbinternaladminmsgs__lodel_scripts_tpl_desk_html;
QUERY: SELECT COUNT(*) AS nbresults
FROM lodel_internal_messaging
WHERE (recipient = 'lodelmain-1' && status = 1)
MYSQL ERROR: Table 'revues_flotest.lodel_internal_messaging' doesn't exist

Soit, on rajoute la table, qui est présente dans la base "mère" de lodel.

Vient ensuite un gros lot de 
` BLOB/TEXT column 'altertitle' can't have a default value`
Eh oui, Mysql n'aime pas les valeurs par défaut sur les champs TEXT/BLOB avec pour raison éventuelle la sauvegarde de mémoire étant donné que chaque entrée de ce type est un objet.

Ensuite, de mémoire, version raccourcie, soit, pas de valeur par défaut. Plus tard, au choix d'un modèle éditorial, celui de revues.org 'field xxx doesn't have a default value', on les ajoute sur le modele de base de données du modèle. Ensuite, arrive une fonction manquante `loop_solr()` et ça continue ainsi encore et encore ....

Question bête, comment installer un lodel fonctionnel !?

**Comment by arnaudcordier** [comment]
> Création d'un site
> Error (Internal Error) in file '/var/www/html/lodel/scripts/class.siteManage.php' on line 326 : SQL ERROR : Field 'langdef' doesn't have a default value

Cela devrait être résolu par 916ab243becdc6e9e01e188ad531fcb75a989025

> il s'avère qu'il manque carrément une fonction loop_errors_createtables

Résolu par 49db6dbfa014c8ec3cb6ba596c45f6a650c79ea4

> Internal error in file /var/www/html/lodel/scripts/view.php(579) : eval()'d code on line 71;
LOOP: nbinternaladminmsgs__lodel_scripts_tpl_desk_html;

Résolu par acbff4d96eeb3fed6affe9983153b9022c5ac2b0

> Vient ensuite un gros lot de
BLOB/TEXT column 'altertitle' can't have a default value

masqué par 79df35094687421389c0934f0dac2699f97941dd

> Ensuite, arrive une fonction manquante loop_solr()

Je ne sais pas d'où vous tirez vos templates mais nous ne distribuons pas de template avec une boucle solr, je ne peux pas répondre à ce genre de demande.

**Comment by loicjaouen** [comment]
même erreur 'Création d'un site' à partir du tar.gz téléchargé sur [SourceSup](https://sourcesup.renater.fr/frs/?group_id=193) lien direct du site [lodel.org](http://lodel.org/).
Si cette version est plus récente, ça serait pas mal de changer le lien sur [lodel.org](http://lodel.org/)
