### ISSUE TITLE
BOURRE DE BUG !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by tomboul** [OpenEdition/lodel#62]
tout est dans le titre,
les procédures d'installation sont bourrées de bug !!!
est ce fait exprès ??????????
ils sont parfois tellement gros qu'on se le demande ...
la liste est tellement longue, si je la déploie ici et que personne ne répond (ce qui semble être le cas), ce long et fastidieux travail que j'aurais pourtant bien voulu faire ne servira à rien ...

1 TRES IMPORTANT : il faut php5.5 mini et non php5.x 'du coup j'ai fermé toutes les "issue" précédement signalées)

j'ai corrigé des plantages dans l'importation de modèle qui n'importait rien sans aucun message d'erreur
J'ai déjà modifié des dizaine d'include non résolu ...
la documentation est totalement incomplète ... 
presque tous les chapitres sont en cours de rédaction
Je ne peux même pas savoir si j'ai correctement fait l'installation, et ce n'est pas le premier package que j'installe !!!! (je connais très bien prestashop ....)

je suis d'accord pour suivre les règles inhérentes aux logiciels libres et partagés,  je suis prêt à y participer mais la communication est NULLE ça fait 26 jours que j'ai laissé des messages ici et AUCUNE RÉPONSE !!!

Si on n'est plus en mesure ou qu'on a plus la capacité de présenter un logiciel en mode partage sur Github alors il faut soit l'enlever soit le signaler, en somme faire le ménage ....

**Comment by pyg77** [comment]
Bonjour @tomboul 
je n'ai rien à voir avec l'équipe de Lodel, et suis moi aussi un utilisateur frustré de n'avoir pu l'installer faute d'une documentation claire (pas grave, je suis finalement parti avec Drupal et ça me convient très bien).

Par contre, en tant qu'animateur de communauté du libre et que développeur de logiciel libre, je peux vous assurer que votre "coup de gueule", aussi légitime soit-il, ne pourra que décourager l'équipe de développement.

Je ne vois que deux cas de figures: 
  * soit l'équipe fait de la rétention d'information (= la version de Lodel sur github n'est pas *exactement* celle utilisée par revues.org & co), par exemple pour vendre de la formation ou autre derrière. Ca serait moralement condamnable, pas très fair play, mais cela n'irait pas pour autant contre les principes du logiciel libre. Il y a un code, il est public et sous licence libre, mais vous n'êtes pas satisfait ? Alors "forkez" le, et créez vous-même votre doc. Sinon, ne l'utilisez pas.
Il n'y a *aucune* obligation de la part de développeur à fournir une version "qui marche", ou une documentation aux petits oignons. 
  * soit l'équipe n'a tout simplement pas les moyens matériels et temporels de compléter cette documentation d'installation. C'est dommage (très dommage, même), car cela les coupe de la possibilité d'élargir la communauté, et donc les contributeurs. Mais c'est leur problème, pas le notre.

Bref, si "ça ne marche pas", soit vous mettez les mains dans le camboui, soit vous passez au logiciel suivant (ce que j'ai fait). Les développeurs seront bien assez grand pour comprendre que si personne d'extérieur ne leur propose des merge request ou ne rejoint une communauté active, c'est justement parce que leur logiciel est ininstallable en l'état de la documentation et des prérequis.

Donc, ce n'est pas, à mon avis, en mettant 52 points d'exclamation dans un titre d'issue que vous allez les motiver. Dans le premier cas ci-dessus, ils ne changeront rien. Dans le second cas, ils auront encore moins envie de prendre le temps de documenter.

Ce ne sont pas les logiciels libres qui manquent.

Bonne journée.

**Comment by tomboul** [comment]
Merci pyg77

ma contribution est un tantinet provocatrice, mais elle est destinée à faire réagir, car il semble n'y avoir personne donc le but est d'avoir une réaction ... 
Elle est destinée aussi aux nouveaux venu qui souhaiteraient utiliser ce code pour les mettre en garde

Et si je me suis permis cette intervention c'est que justement j'ai mis les mains dans le cambouis (j'adore cette expression que j'utilise moi même très souvent). Je n'ai pu que constater l'ampleur vertigineuse des travaux à accomplir pour remettre en état ce logiciel qui a eu pourtant son heure de gloire.Pendant un mois J'ai laissé par mal de messages indiquant des bug et proposant des solutions et je n'ai eu aucune réponse.
J'en ai conclu qu'il fallait intervenir de façon plus directe et plus incisive pour savoir qu'est quelle équipe était derrière et pour savoir si il y a encore un matelot dans le navire ... 

Et je suis vraiment désolé pour le brave matelot  si il existe et qui essaye de tenir la barre tant bien que mal .... On pourra toujours effacer ces messages incendiaire ou les modifier pour être plus constructif ..

**Comment by nahuelange** [comment]
Bonjour,

Allez, j'y laisse mon commentaire, parce que ce genre d'attitude n'a pas à avoir lieu ici (et puis c'est un système de gestion de tickets pas du support utilisateur, il y a une liste de discussion pour ça).
Pour information, j'ai travaillé un certain nombres d'années au Cléo (où l'équipe qui se charge de la maintenance de Lodel travaille).

Déjà, merci @pyg77, comme pour tout logiciel libre il est explicitement dit qu'il est fournit sans garantie de : fonctionnement, support et maintenance.
D'autre part, l'équipe ne fait pas de rétention d'informations (à moins que la politique du Cléo ait changé) et n'en a jamais fait, l'équipe n'a juste pas vraiment le temps de s'occuper de ça.

Lorsque j'étais encore là, nous avons essayé de (ré)activer la communauté de développeurs autour de Lodel (d'où le passage de sourcesup à github), mais le problème est que celle-ci est inexistante ou alors très mal formée aux outils d'aujourd'hui (git, github, patchs, pull requests, …), nous avons dû recevoir seulement deux patchs, qui plus est, étaient pour des versions bien antérieures aux versions de développement qui avaient déjà corrigé la majorité des problèmes. Bref, autant dire qu'à part les gens payés par le Cléo pour faire du travail nécessaire au bon fonctionnement de la plateforme, personne ne participe techniquement à ce projet. On le voit bien au nombre de pull requests qui ont étés proposées sur github.
Il est clair que la documentation a de grande lacunes en terme de mise à jour des parties dépréciées autant que des nouvelles fonctionnalités, cependant, personne de la communauté ne se propose pour la mettre à jour, cette initiative serait, je pense, la bienvenue.

Proposer des solutions ne suffit pas pour une équipe déjà débordée, il faut proposer des pull requests, et j'imagine que l'équipe se fera un plaisir d'accepter, amender, commenter ou refuser celle-ci, mais pour cela, faut-il qu'il y ait des pull requests :-)
Quoi qu'il en soit, lorsque j'étais présent, nous avons toujours été très ouverts à la contribution de personnes externes, malheureusement inexistantes, la majorité (ci ce n'est la totalité) des utilisateurs de positionnent en consommateurs d'un produit, ce qui n'a aucun intérêt (technique ou de documentation) sur l'amélioration du projet, c'est limite contre productif, car ces personnes là ne prennent même pas le temps de lire les dizaines de réponses déjà faites au sujet des problèmes qu'elles rencontrent, et là je passe les problèmes ServOO et OTX qui n'ont strictement rien à voir avec Lodel.

Tout ça pour en venir au fait, que pour prendre contact avec l'équipe, il suffit de s'inscrire, par exemple, aux listes de discussions suivantes, en fonction des besoins:

https://groupes.renater.fr/sympa/info/lodel-users
https://groupes.renater.fr/sympa/info/lodel-devel

Mais par pitié, il faut éviter de faire ce genre de «tickets» totalement contre productifs, qui ont tendance à énerver tout le monde. Ça n'est pas comme ça que les choses évolueront. Et comme dit @pyg77, rien ne t'empêche de forker le projet, Lodel est publié sous licence GPL avec les libertés et contraintes que ça apporte.

**Comment by tomboul** [comment]
Mon intention depuis un mois était de collaborer ...
Après mes multiples sur le rapport de bug,et les messages d'autre personnes cherchant à collaborer mais restés sans réponses, j'avais l'impression d'avoir à faire un une équipe fantôme ...

Je ne réclame rien, mais si on propose un travail collaboratif alors il faut une équipe, si cette équipe n'existe pas il faut le signaler et c'est ce que je fais. En faisant cela je collabore ....
C'est ma façon de collaborer. Je ne réclame rien et je mets en garde ceux qui veulent s'aventurer sur lodel en les prévenant que le logiciel est à un stade très peu avancé ...

La preuve que j'ai eu raison d'agir ainsi, après un moi j'ai enfin des réponses !!!

**Comment by nahuelange** [comment]
Le fait que j'ai répondu, est que ce message m'a irrité au plus haut point, ça aurait été un autre projet que je suis ma réaction aurait été la même.
Un rapport de bug, c'est bien, un fix c'est mieux. L'équipe ne rencontre pas forcément ce problème, et n'a pas besoin de prendre du temps pour le fixer.
D'autre part, une communauté se créer aussi du fait que les utilisateurs se répondent entre eux, on en revient à ce que j'ai dit tout à l'heure: les utilisateurs se positionnent en consommateurs.

De toutes façons, je ne fais plus partie de «l'équipe» depuis début 2014, je ne sais pas où en est le projet en interne. @arnaudcordier étant parti du Cléo en Février/Mars, je ne sais pas qui est en charge de la maintenance maintenant. Il est possible que ce soit @yweber (seul à commiter depuis le départ de @arnaudcordier).

**Comment by pyg77** [comment]
Bon, et bien je pense qu'on a réussi à faire avancer un peu les choses : 
  * on sait pourquoi l'équipe ne répond pas (manque de temps + prise en main git), 
  * et l'équipe saura pourquoi elle n'a pas de retours (impossible de proposer des pull request si on n'arrive même pas à installer le logiciel, je rejoins évidemment @tomboul sur ce point ).

Pour moi, ça reste dommage, car Lodel reste un très bon produit, mais - avis perso - il est hors de question que je passe 1 journée complète à tenté de l'installer (quand j'avais essayé, fin 2014, j'avais remonté un bug qui a été corrigé 5 mois plus tard. Evidemment, entre temps, je suis passé à autre chose).

**Comment by nahuelange** [comment]
Rien n'empêche de faire des pull requests sur le processus d'installation :-)
Mais je comprends la problématique, qui se justifie.

**Comment by jfriviere** [comment]
Bon, et bien un réponse de l'équipe du cléo. 
Effectivement nous manquons de monde pour nous occuper de ce logiciel. Et effectivement depuis le départ de @arnaudcordier on est encore plus en peine sur ce point.

Je vous donne quand même 2 infos.

1#  j'ai envoyé ce message sur la liste https://groupes.renater.fr/sympa/info/lodel-users il y a quelques semaines qui éclaircira peut-être un peu les choses entre Revues.org et Lodel.

> 
> ---------- Message transféré ----------
> De : Jean-François Rivière <jean-francois.riviere@openedition.org>
> Date : 22 avril 2016 à 16:18
> Objet : Précisions diverses sur Lodel
> À : lodel-users@groupes.renater.fr
> 
> 
> Bonjour,
> 
> Il y a beaucoup de questions et de problèmes signalés sur la liste lodel-users ces dernières semaines. Je vais essayer d'apporter quelques précisions et éléments de contexte sur Lodel. 
> 
> Lodel 
> Lodel est un logiciel libre. Il est développé à 99.9% par le Cléo qui produit les plateformes d'OpenEdition (dont Revues.org et OpenEdition Books). Le code est partagé sous licence GPL 2 sur GitHub mais notre équipe est réduite et a beaucoup évolué ces dernières années. Nous disposons de peu de temps pour répondre aux questions posées sur la liste. 
> Nous remercions au passage tous les abonnés qui prennent le temps de proposer des réponses.
> 
> Lodel est peu documenté. Lire le code et les logs d'erreur est souvent la seule méthode pour résoudre les problèmes.
> Pour lire les logs d'erreurs, il faut y avoir accès, ce qui n'est pas toujours le cas dans les hébergements mutualisés.
> Lodel n'est pas bien "packagé". Nous l'utilisons au Cléo sous Debian, mais nous n'avons pas testé d'autres environnements d'installation. Dans d'autres configurations, il est possible que des adaptations soient nécessaires.
> Lodel existe depuis longtemps. La base de Lodel date de la première moitié des années 2000. Il a évolué sur cette base. Il est daté, en particulier dans sa conception et dans certaines librairies utilisées (pear par exemple).
> 
> Donc pour résumer, la prise en main n'est pas simple et il faut disposer de compétences informatiques et de persévérance pour l'utiliser...
> 
> Machine virtuelle
> Comme l'a indiqué Bruno Cénou dans un précédent message, nous allons bientôt distribuer un machine virtuelle avec une installation fonctionnelle de Lodel + OTX. Elle permettra de tester facilement le logiciel et de comparer sa configuration avec une installation fonctionnelle.
> 
> Maquette
> La maquette utilisée par Revues.org n'est pas distribuée avec Lodel. La maquette distribuée a près de 15 ans et peut difficilement être utilisée en l'état. Pour produire un site avec Lodel, il faut donc prévoir de réaliser sa propre maquette en utilisant le langage de template de Lodel : Lodelscript. La documentation Lodelscript est disponible à cette adresse https://github.com/OpenEdition/lodel/wiki/Lodelscript et la maquette distribuée peut servir d'exemple.
> 
> Autres services utilisés dans Revues.org mais qui ne sont pas compris dans Lodel
> Le Cléo produit pour la plateforme Revues.org des sites de revues basés sur Lodel, mais aussi des services qui ne sont pas produits par Lodel : entrepôt OAI, moteur de recherche,  versions pdf et epubs des articles notamment. Ces fonctionnalités sont développées avec d'autres technologies. Vous ne les trouverez pas dans Lodel.
> 
> OTX
> OTX est l'application qui permet la conversion de fichiers de traitement de texte stylés en fichiers XML-TEI compatibles avec le modèle éditorial "Revues.org" distribué dans Lodel.
> Le projet d'écriture de l'application OTX prévoyait au départ une totale adaptabilité d'OTX au modèle éditorial de Lodel. En spécifiant des informations sous forme de XPath dans le modèle éditorial du site Lodel, OTX devrait être capable de convertir le document de traitement de texte stylé en XML TEI sur la base de ce XPath.
> Concrètement, OTX n'est que partiellement dynamique. Certaines spécifications de XPath dans le modèle éditorial de Lodel sont prises en compte par OTX, d'autres non. La liste des cas non-reconnus n'est pas documentée. Nous avons choisi de publier Lodel 1.0 et OTX 1.0 malgré cette limite.
> 
> Le Cléo ne propose pas de service de conversion ouvert comme c'était le cas avec ServOO (logiciel de conversion utilisé avec Lodel 0.8/0.9).
> Pour importer des documents de traitement de texte, il faut donc installer aussi OTX. 
> 
> Comme pour Lodel, nous utilisons OTX dans un environnement Debian 7/8. Nous ne l'avons pas testé dans d'autres environnements. En particulier, nous ne savons pas s'il est utilisable dans un environnement Windows.
> 
> Comme l'a indiqué Bruno Cénou dans son précédent mail, nous allons publier prochainement une version corrigée d'OTX (sans utilisation de classe PEAR). Nous vous recommandons d'attendre cette correction avant de poursuivre vos essais.
> 
> Maison des revues
> La maison des revues http://maisondesrevues.org/ est le site d'accompagnement éditorial des revues de Revues.org qui publient sur la plateforme avec Lodel mais bénéficient également des autres services cités plus haut (pdf, epub, oai, maquette...). Donc cette documentation contient des informations relatives à Lodel mais aussi des informations relatives à d'autres services de la plateforme.
> 
> Donc, vous l'aurez compris, si vous chercher une solution simple à mettre en œuvre, Lodel n'est probablement pas la meilleure option.
> 
> Lodel 2
> Je termine en précisant que le Cléo continue d'utiliser Lodel pour mettre en œuvre OpenEdition et que nous avons commencé à travailler sur une nouvelle version (Lodel 2) qui sera distribuée sur GitHub sous Licence AGPL.
> Elle ne sera pas publiée avant un an.
> C'est une version réécrite from scratch en python. Nous publierons des scripts permettant la migration des données de Lodel 1 vers Lodel 2, mais il faudra reprendre l'intégration des templates faits  pour Lodel 0.8-1.0. La migration sera possible mais il est probable qu'elle ne sera pas triviale.
> 
> Dans l'immédiat, nous espérons que la machine virtuelle et la correction d'OTX vous permettront d'avancer.
> 
> Cordialement,
> 
> -- 
> Jean-François Rivière

2# nous avons mis en ligne la machine virtuelle dont il est question dans le mail précedent sous différents formats : raw, qcow2 et vmdk. Elles devraient permettre une prise en main de l'environnement Lodel/OTX : http://lodel.org/downloads/vms/

JF Rivière

**Comment by tomboul** [comment]
content et soulagé qu'il existe encore un matelot dans le navire ...
Au moins c'est clair, je pense qu'il faudrait mettre à jour le wiki juste pour informer d'éventuels futurs utilisateurs des conditions d'utilisations et projets en cours et futurs énoncés ici.
Désolé pour le ton un peu provoque, mais je dois constater que grâce à cela, aujourd'hui j'ai énormément avancé !!
