### ISSUE TITLE
Formattage javascript intempestif

### ISSUE THREAD

**Issue by zerline** [OpenEdition/lodel#87]
Bonjour

J'essaie actuellement de migrer un site vers la version master.

Il me semble constater que le nouveau moteur formatte joliment les lignes de HTML, ce qui n'est pas un mal, mais sauf quand ces lignes sont inscrites dans du code javascript car alors cela le rend invalide ! (les chaînes de caractères non terminées sur la même ligne sont interdites en JS).  Une solution pourrait être d'ajouter des '\\' au bout des lignes, avant chaque saut de ligne.

Merci d'avance pour votre réponse. 
Cordialement

**Comment by HichamBenjelloun** [comment]
Bonjour ! Il est actuellement possible de désactiver cette indentation avec l'attribut `NOINDENT`, par exemple:
```
<CONTENT VERSION="1.0" LANG="fr" CHARSET="utf-8" NOINDENT="1"/>
```

**Comment by zerline** [comment]
OK cela règle mon problème en effet. Merci.

**Comment by zerline** [comment]
Le Tue, 31 Oct 2017 10:21:21 +0000 (UTC),
Hicham Benjelloun <notifications@github.com> a écrit :

> Bonjour ! Il est actuellement possible de désactiver cette
> indentation avec l'attribut `NOINDENT`, par exemple: ```
> <CONTENT VERSION="1.0" LANG="fr" CHARSET="utf-8" NOINDENT="1"/>
> ```
> 

bonjour
j'ai fermé le ticket, mais c'est peut-être dommage : votre réponse n'y
est pas...

cordialement,

-- 
Odile Bénassy
http://fluidinfo.fr

**Comment by zerline** [comment]
OK cela règle mon problème en effet. Merci.
