### ISSUE TITLE
Impossible d'ajouter une publication

### ISSUE THREAD

**Issue by lucaguindani** [OpenEdition/lodel#89]
Bonjour,

J'ai installé le CMS sur un environnement local (docker). Il semble fonctionner sans trop de soucis. Cependant, je n'ai pas la possibilité d'ajouter une publication à un site que je viens de créer. J'ai un utilisateur de niveau administrateur pourtant, mais l'option "Ajouter" semble grisée, comme si je n'avais pas les droits suffisants (voir images jointe).

Ai-je manqué quelque chose ?

![publication](https://user-images.githubusercontent.com/1675064/33271541-d160906c-d387-11e7-954a-8e39d80739d5.png)

**Comment by PatGendre** [comment]
bonjour,
vous n'avez sans doute pas chargé de modèle éditorial : dans Administration, importer un modèle éditorial, choisir le modèle de revues. Vous pourrez ensuite créer des objets correspondant à ce modèle.
Cordialement,
Patrick Gendre
OpenEdition

**Comment by lucaguindani** [comment]
C'était bien le modèle éditorial qui n'était pas chargé.

Merci pour votre réponse.

**Comment by PatGendre** [comment]
de rien, bons tests !
