### ISSUE TITLE
Question lodel 3

### ISSUE THREAD

**Issue by roundge** [OpenEdition/lodel#93]
Bonjour, 

J'envisage d'utiliser Lodel dans mon travail.
Lodel datant un peu, je me demandais si vous étiez sur le développement d'une nouvelle version de Lodel (lodel 3) ? 
Pourquoi ne pas avoir utilisé de framework comme symfony, laravel, cake-php, codeigniter,... pour le développement ? Envisagez vous cette possibilité pour une future version ?

Merci d'avance,
Best regards
Etienne R.

**Comment by PatGendre** [comment]
bonjour,
nous avons une réflexion en cours pour moderniser le code Lodel, l'utilisation de symfony ou laravel est envisagée, mais à ce stade aucune décision n'est prise. Actuellement notre principale préoccupation est de recruter, ce qui n'est pas facile!
Cordialement
Patrick Gendre

**Comment by roundge** [comment]
Bonjour, 
L'utilisation d'un framework est une excellente idée pour une maintenabilité et un travail collaboratif plus aisée. Nous utiliserons dans un premier temps Lodel dans sa version 1. La possibilité de créer des plugins nous permettra d'adapter le logiciel à d'éventuels besoins supplémentaires. Soyez sûrs que si un plugin intéressant était développé nous ne manquerons pas de vous le soumettre. 
Merci pour votre réactivité,
Cordialement,
Étienne R.
